Th17 - New Th, Troop, Spell, Hero, & Equipment
mathsman5133/coc.py pull request #248
Opened 2024-11-26 12:39 UTC by MagicTheDev

updated relevant static files & enums

2024-12-03 09:53 UTC, doluk requested changes

2024-12-03 09:53 UTC, doluk commented on coc/enums.py
> +HOME_BASE_HERO_ORDER = ["Barbarian King", "Archer Queen", "Grand Warden", "Royal Champion", "Minion Prince"]
I would vote to keep it the order of unlocking, matching the ingame order in the hero hut, so minion prince in the middle

2024-12-03 09:53 UTC, doluk commented on coc/enums.py
> +    "Dark Orb"
Please add the lavaloon puppet

2024-12-03 09:53 UTC, doluk commented on coc/static/update_static.py
> -import zstandard
good catch with the duplicate imports

2024-12-03 09:53 UTC, doluk commented on coc/static/update_static.py
> +    import asyncio
can we move the imports all to the top? there is another one in decompress

2024-12-06 22:12 UTC, mathsman5133 commented
Happy to hear thoughts, but does anyone actually look through the json files? Ie. do we need them "beautified"? 

I did a quick test and just about halved the `buildings.json` file by loading and re-dumping the contents into a single line json file.

If people actually look through them I don't hugely mind, but if we have the option it'd be nice to keep this static data small-ish for pypi and releases, and not having enormous git diffs.

2024-12-24 13:10 UTC, doluk commented on coc/static/update_static.py
> +    import asyncio
still pending

2024-12-24 13:38 UTC, doluk requested changes

2024-12-24 13:38 UTC, doluk commented on coc/abc.py
> +    def _load_json_meta(cls, json_meta: dict, id, name: str, lab_to_townhall):
Can we maybe add here some documentation for the future outlining the structure of json_meta?

2024-12-24 13:38 UTC, doluk commented on coc/abc.py
> +        required_townhall_levels = [json_meta.get(level).get("RequiredTownHallLevel") for level in levels_available]
does this already reflect the hero hall dependency instead of the former th one?

2024-12-24 13:38 UTC, doluk commented on coc/abc.py
> +            #Not interested if it doesn't have a TID, since it likely isn't a real troop.
```suggestion
            # Not interested if it doesn't have a TID, since it likely isn't a real troop.
```
I would revert this one

2024-12-24 13:38 UTC, doluk commented on coc/abc.py
> +                id=(id := id + 1),
Fancy one, but not necessarily the most easy one to read

2024-12-24 13:38 UTC, doluk commented on coc/client.py
>              elif supercell_name =='Smithy':
We need this for the hero hall too

2024-12-24 13:38 UTC, doluk commented on coc/troop.py
> +from email.policy import default
Random import?

2024-12-24 13:38 UTC, doluk commented on coc/static/townhall_levels.json
> +    "5": {
what function does the inner dict level of "5" aka attackCost have?

2025-01-01 23:10 UTC, MagicTheDev commented on coc/abc.py
> +    def _load_json_meta(cls, json_meta: dict, id, name: str, lab_to_townhall):
yea, and maybe a last refactor of it would be good, to work out the last kinks of turning it into "normal" json

perhaps, like pydantic would be good for this? being able to define the structure & it'll ignore any undefined fields +  can reference that class instead :)

2025-01-01 23:11 UTC, MagicTheDev commented on coc/abc.py
> +        required_townhall_levels = [json_meta.get(level).get("RequiredTownHallLevel") for level in levels_available]
next version, required townhallLevel does work, its more along the lines of a "lab" being needed to be added for the heroes

2025-01-01 23:12 UTC, MagicTheDev commented on coc/static/townhall_levels.json
> +    "5": {
parsing issues 👍🏻

2025-01-01 23:25 UTC, doluk approved these changes

2025-01-02 10:55 UTC, doluk approved these changes

2025-01-02 11:08 UTC, merged